# Generated by Django 3.1.4 on 2020-12-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=200)),
                ('content', models.TextField(default='', max_length=2000)),
            ],
        ),
    ]
